site_name: My Docs
theme:
   name: material
   features:
      - navigation.tabs
   palette:
      primary: light green
      accent: indigo
nav:
   - Início: ./index.md
   - Apresentações:
        - Primeira Apresentação: ./apresentacoes/apresentacao1.md
